<?php

namespace DS\InternauteBundle\Entity;

/**
 * LienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LienRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLiensActif()
	{
            $query = $this->_em->createQuery(
            'SELECT L.id, L.titre, L.description,
            L.logo, L.adresse,L.actif
            FROM DSInternauteBundle:Lien L
            where L.actif = 1'
            );
            
        $ref = $query->getResult();
        return $ref;
	}
}

