<?php

namespace DS\InternauteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * visiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $ip
     * @param $pageVisitee
     * @param $langue
     * @return mixed
     */
    function majVisite($em, $DateHeure, $ip, $pageVisitee, $langue){

        // on traite les données
        $pageVisitee = utf8_decode($pageVisitee);

        // on met à jour la base
        $visite = new Visite();
        $visite->setVisDate($DateHeure);
        $visite->setVisIp($ip);
        $visite->setVisPage($pageVisitee);
        $visite->setVisLangue($langue);

    //    $this->majVisite->bindParam(':dateHeure',$dateHeure);
     //   $this->majVisite->bindParam(':ip',$ip,PDO::PARAM_STR);
     //   $this->majVisite->bindParam(':pageVisitee',$pageVisitee,PDO::PARAM_STR);
     //   $this->majVisite->bindParam(':langue',$langue,PDO::PARAM_STR);
     //   $res = $this->majVisite->execute();
     //   return $res;


        $em->persist($visite);
        $em->flush();

    }
}
