<?php

namespace Proxies\__CG__\DS\InternauteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Visite extends \DS\InternauteBundle\Entity\Visite implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'DS\\InternauteBundle\\Entity\\Visite' . "\0" . 'id', '' . "\0" . 'DS\\InternauteBundle\\Entity\\Visite' . "\0" . 'visDate', '' . "\0" . 'DS\\InternauteBundle\\Entity\\Visite' . "\0" . 'visIp', '' . "\0" . 'DS\\InternauteBundle\\Entity\\Visite' . "\0" . 'visPage', '' . "\0" . 'DS\\InternauteBundle\\Entity\\Visite' . "\0" . 'visLangue');
        }

        return array('__isInitialized__', '' . "\0" . 'DS\\InternauteBundle\\Entity\\Visite' . "\0" . 'id', '' . "\0" . 'DS\\InternauteBundle\\Entity\\Visite' . "\0" . 'visDate', '' . "\0" . 'DS\\InternauteBundle\\Entity\\Visite' . "\0" . 'visIp', '' . "\0" . 'DS\\InternauteBundle\\Entity\\Visite' . "\0" . 'visPage', '' . "\0" . 'DS\\InternauteBundle\\Entity\\Visite' . "\0" . 'visLangue');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Visite $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisDate($visDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisDate', array($visDate));

        return parent::setVisDate($visDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisDate', array());

        return parent::getVisDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisIp($visIp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisIp', array($visIp));

        return parent::setVisIp($visIp);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisIp', array());

        return parent::getVisIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisPage($visPage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisPage', array($visPage));

        return parent::setVisPage($visPage);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisPage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisPage', array());

        return parent::getVisPage();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisLangue($visLangue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisLangue', array($visLangue));

        return parent::setVisLangue($visLangue);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisLangue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisLangue', array());

        return parent::getVisLangue();
    }

}
